# Generated by Django 4.1 on 2022-09-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_user',
        ),
    ]
