# Generated by Django 4.1 on 2022-09-06 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPosts', '0003_customuser_blocked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, related_name='blocked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
